### ISSUE TITLE
when i running in linux centos 7,have a error message

### ISSUE THREAD

**Issue by startybai** [michaeldmoore/CSVServer#2]
[root@my-bai CSVServer]# node CSVServer.js
/usr/share/nginx/html/CSVServer/CSVServer.js:59
async function query(target) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

can you help me reslove this issue ,thank you

**Comment by michaeldmoore** [comment]
Make sure you have the latest version of node installed.  Someone else had
a similar issue and this resolved the problem.
